baseURL = 'https://blog.romancollinge.io/'
languageCode = 'en-gb'
title = "Roman's Dev Blog"
theme = 'nightfall'

[params]
user = "home"
hostname = "romancollinge.io"

[params.author]
name = "Roman Collinge"
email = "romancolling@outlook.com"

[[params.social]]
key = 0
name = "Github"
url = "https://github.com/roman-collinge"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "Twitter"
url = "https://www.example.com"

[[params.social]]
key = 3
name = "Youtube"
url = "https://www.example.com"

[[params.social]]
key = 4
name = "Newsletter"
url = "https://www.example.com"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"

